/*
 * Name: Socket Programming - Server.
 * Author: Arafat Hossain Ar
 * Date: 1/05/2020
 * All right reserved. Don't copy single line of code without permission.
 */
package socketprogramming;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.ServerSocket;
import java.net.Socket;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Arafat Hossain Ar
 */
public class Server extends javax.swing.JFrame {

    static ServerSocket serversocket;
    static Socket clientsocket;
    static BufferedReader cin, stdin;
    static PrintWriter cout;
    static String str;
    static DateFormat dateFormat = new SimpleDateFormat("HH:mm");

    public Server() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl1 = new javax.swing.JLabel();
        btnhelp = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputbox = new javax.swing.JTextArea();
        inputbox = new javax.swing.JTextField();
        btnsend = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Server");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setBackground(new java.awt.Color(255, 0, 51));
        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketprogramming/image/iconfinder_facebook_live_icon_1083837.png"))); // NOI18N
        lbl1.setText("Live Chat Server");
        jPanel1.add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, -1));

        btnhelp.setBackground(new java.awt.Color(0, 0, 0));
        btnhelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketprogramming/image/iconfinder_19_330401.png"))); // NOI18N
        btnhelp.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnhelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhelpActionPerformed(evt);
            }
        });
        jPanel1.add(btnhelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 3, 59, 30));

        btnexit.setBackground(new java.awt.Color(0, 0, 0));
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketprogramming/image/iconfinder_exit_38999.png"))); // NOI18N
        btnexit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 3, 54, 30));

        outputbox.setEditable(false);
        outputbox.setColumns(20);
        outputbox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        outputbox.setLineWrap(true);
        outputbox.setRows(5);
        outputbox.setWrapStyleWord(true);
        jScrollPane1.setViewportView(outputbox);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 39, 380, 440));

        inputbox.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        inputbox.setToolTipText("Your text");
        inputbox.setDragEnabled(true);
        jPanel1.add(inputbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 320, 40));

        btnsend.setBackground(new java.awt.Color(0, 0, 0));
        btnsend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/socketprogramming/image/iconfinder_web_9_3924904.png"))); // NOI18N
        btnsend.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendActionPerformed(evt);
            }
        });
        jPanel1.add(btnsend, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 480, 60, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhelpActionPerformed
        String msg = "<html><big><font color = 'red'>Socket Programming</font></big><hr>"
                + "<hr><b><i> Author: Arafat Hossain Ar </i></b><br/>"
                + "<b><i> Creation Date: 01-04-2020 </i></b><br/>"
                + "<b><i>Version: 1.0</i></b><br/>"
                + "<b><i>Type: Server</i></b><br/>"
                + "<b><i>Join Me: fb.com/Arafathossain000</i></b><hr><hr>"
                + "</html>";
        JOptionPane.showMessageDialog(this, msg, "About", -1);
    }//GEN-LAST:event_btnhelpActionPerformed

    private void btnsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendActionPerformed

        if (evt.getSource() == btnsend) {
            str = inputbox.getText();
            cout.println(str);
            // outputbox.setText(outputbox.getText() + dateFormat.format(new Date()) + " Server: " + str + "\n");
            outputbox.setText(outputbox.getText() + "#S: " + str + "\n");
        }
        inputbox.setText("");


    }//GEN-LAST:event_btnsendActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                new Server().setVisible(true);
            }
        });
        String ch = "\u24B8 ";
        try {
            serversocket = new ServerSocket(1000);
            System.out.println("Waiting for client on port " + serversocket.getLocalPort() + "...");
            clientsocket = serversocket.accept();
            System.out.println("Connected to " + clientsocket.getRemoteSocketAddress());
            cin = new BufferedReader(new InputStreamReader(clientsocket.getInputStream()));
            cout = new PrintWriter(clientsocket.getOutputStream(), true);

            while (true) {
                str = cin.readLine();
                //   outputbox.setText(outputbox.getText() + dateFormat.format(new Date()) + " Client: " + str + "\n");
                outputbox.setText(outputbox.getText() + "#C: " +str + "\n");
            }
        } catch (IOException e) {
            System.out.println(e);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnhelp;
    private javax.swing.JButton btnsend;
    private javax.swing.JTextField inputbox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JLabel lbl1;
    private static javax.swing.JTextArea outputbox;
    // End of variables declaration//GEN-END:variables
}
